### ISSUE TITLE
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/torch/lib/THC/THCGeneral.c:70

### ISSUE THREAD

**Issue by hubin111** [piergiaj/super-events-cvpr18#1]
help me
    return model.cuda( )

**Comment by hubin111** [comment]
Traceback (most recent call last):
  File "/home/hubin/super-events-cvpr18/train_model.py", line 249, in <module>
    rgb_results = eval_model(rgb_model, dataloaders['val'], baseline=True)
  File "/home/hubin/super-events-cvpr18/train_model.py", line 121, in eval_model
    for data in dataloader:
  File "/home/hubin/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "/home/hubin/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 242, in __init__
    self._put_indices()
  File "/home/hubin/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 290, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/hubin/anaconda2/lib/python2.7/site-packages/torch/utils/data/sampler.py", line 119, in __iter__
    for idx in self.sampler:
  File "/home/hubin/anaconda2/lib/python2.7/site-packages/torch/utils/data/sampler.py", line 50, in __iter__
    return iter(torch.randperm(len(self.data_source)).long())
RuntimeError: invalid argument 1: must be strictly positive at /pytorch/torch/lib/TH/generic/THTensorMath.c:2247

**Comment by prwani-microsoft** [comment]
Please install Pytorch using right command by selecting versions of python and OS @ "https://pytorch.org/". This solve above error for me...

**Comment by Guzzler** [comment]
If the error is a cuda runtime error(38): no CUDA-capable device you might want to change the default arg passed as the gpu parameter from '1' to '0' as by default most single GPU systems have their device index as 0 not 1. This fixed the problem for me.

**Comment by alixiansen91** [comment]
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /tmp/pip-req-build-4baxydiv/aten/src/THC/THCGeneral.cpp:50  I can't find the location where i can modify the gpu from '1' to '0'
